:BAL: Bal 3000 Turbo Max Pro
:title: {BAL} Requirements Book
:project: Project
:original_template_version: 1.23.4
:original_template_author: J.-M. Bruel
:original_template_email: bruel@irit.fr
:original_template_organization: IRIT/CNRS - University of Toulouse, France
:original_template_icons: font
:original_template_toc: macro

:version: 0.1.0
:author: B. Christopher & I. Augustin & M. Enzo
:email: christopher.biamonte@etu.univ-tlse2.fr & augustin.iamundo@etu.univ-tlse2.fr & enzo.mauger@etu.univ-tlse2.fr
:organization: Master ICE-LD - University of Toulouse, France
:toc: macro

//--------------------------- PDF version
:doctype: book
//:title-page-background-image: image::pegs.svg[pdfwidth=60%]
// :title-logo-image: image::pegs.svg[top=1%, align=left, pdfwidth=2.5in]
//:back-cover-image: image::pegs.svg[pdfwidth=160%]
:method: pass:[<b>PEGS</b>]
ifdef::pdf-backend[]
:method: PEGS
endif::[]

= {title}
{author},{email}
{version} -- {localdate}

//--------------------------- Glossary & Definitions
// URLS
:hb-url: https://se.inf.ethz.ch/requirements/
:companionURL: https://formalrequirements.github.io/companionRequirements
:HandbookPDF: https://link.springer.com/content/pdf/10.1007/978-3-031-06739-6.pdf
:companionGit: https://github.com/FormalRequirements/requirements-handbook
:handbook: link:{hb-url}[Handbook]
:emptysec: icon:warning[] The section does not contain any information at this point.

// ICONS
:check: icon:check-circle[]
:nocheck: icon:times-circle[]
:missing: icon:bug[]
// GLOSSARY ENTRIES
:Book: <<Book, Book>>
:Catalog:  <<Catalog, Catalog>>
// PERSONS ENTRIES
:jmb: https://jmbruel.netlify.app[J.-M. Bruel]:


[NOTE]
====
This document follows the requirements book structure presented in the {HandbookPDF}[Handbook of requirements and business analysis].
====

*CHANGELOG*

//----------------------------------------------
[cols="1,1,3",,options="header"]
|===
| Version | Date | Comment 
//----------------------------------------------
| 1.0    | 2021-02-01 | Initial draft by {jmb}
| 1.23   | 2023-01-28 | Updated by {jmb} after  publication of the {Handbook}
| 1.23.1 | 2023-08-17 | Correct S.4 title, by {jmb} 
| 1.23.2 | 2023-08-25 | Integrating the minimum principle, by {jmb} 
| 1.23.3 | 2023-08-27 | Adding note for each chapters and reordering to be consistent with the {Handbook}, by {jmb} 
| 1.23.4 | 2023-12-22 | Adding numbering options, by {jmb} 
//| _{version}_ | _{localdate}_ | _Current PDF version, by {jmb}_
|=== 
//----------------------------------------------

toc::[]
//------------------------------------
// GOALS book
//
// Template for requirement:
//---- Requirement
//[[gx-keyword]] 
//`{counter:gx}`
// Requirement

// {missing} [Corresponding Artifact]
//---- 
//------------------------------------

== Goals

// [NOTE]
// ====
// Goals are "needs of the target organization, which the system will address". 
// While the development team is the principal user of the other books, the Goals book addresses a wider audience: essentially, all stakeholders (see {Handbook}).

// It must contain enough information to provide — if read just by itself — a general sketch of the entire project. 
// To this effect, chapter G.3 presents a short overview of the system and <<G1,G.1>> will typically include some key properties of the environment. 
// As it addresses a wide readership, it should be clear and minimize the use of specialized technical terms. 
// Together, <<G1,G.1>>, <<G2,G.2>> and <<G3,G.3>> describe the rationale for the project. 
// It is important to state these justifications explicitly. 
// Typically, they are well understood at the start of the project, but management and priorities can change  (see {Handbook}).
// ====

[[G1]]
=== G.1 Context and overall objectives

// NOTE: High-level view of the project: organizational context and reason for building a system (see {Handbook}).

// WARNING: This chapter should not be empty (following the _Minimum Requirements Outcome Principle_, p.27 of the {handbook}).

// //---- Requirement
// [[g1-exp1]]
// `{counter:g1}`
// Example of numbered requirement (see <<g1-exp2, another example>>).
// //---- 

// //---- Requirement
// [[g1-exp2]]
// `G.1.{counter:g1}`
// Another example of numbered requirement, more explicit in its numbering (see <<g1-exp1, another example>>).
// //---- 

//---- Requirement
[[g1-exp1]]
^`G.1.{counter:g1}`^
The {BAL} is a completly new approach on mailing and mailing box. It aims to fix traditionnal issues with mailing boxes and improve the experience for the end user.
//---- 

//---- Requirement
[[g1-exp2]]
^`G.1.{counter:g1}`^
The {BAL} will allow the end user to get the content of the received mails at any given point in time and at any given place.
//----

[[G2]]
=== G.2 Current situation

// NOTE: Current state of processes to be addressed by the project and the resulting system (see {Handbook}).

//---- Requirement
[[g2-exp1]]
^`G.2.{counter:g2}`^
The {BAL} is currently at its prototype stage, solutions to accomplish the goals are yet to be decided.
//----

[[G3]]
=== G.3 Expected benefits

// NOTE: New processes, or improvements to existing processes, made possible by the project results (see {Handbook}).

//---- Requirement
[[g3-exp1]]
[#g3-exp1]
^`G.3.{counter:g3}`^
The first benefit granted by the {BAL} is to receive the content of any mail without having to interact with the physical system.
//----

//---- Requirement
[[g3-exp2]]
^`G.3.{counter:g3}`^
Since the system will allow the user to avoid having to get his mails redirected, one induced benefit from the <<g3-exp1, first benefit>> is a decrease in usage of paper, cardboard and all sorts of adhesive.
//----

=== G.4 Functionality overview

NOTE: Overview of the functions (behavior) of the system. Principal properties only (details are in the System book) (see {Handbook}).

//---- Requirement
[[g4-exp1]]
^`G.4.{counter:g4}`^
The system shall read any standard A4 letter within any standard envelope.
//----

//---- Requirement
[[g4-exp2]]
^`G.4.{counter:g4}`^
The system shall recognig4ze and distinguish well-known packages format (e.g. Amazon/UPS deliveries).
//----

//---- Requirement
[[g4-exp3]]
^`G.4.{counter:g4}`^
Convert the content of read letter and sent it by email to the user.
//----

//---- Requirement
[[g4-exp4]]
^`G.4.{counter:g4}`^
Allow user to register a set of 5 emails maximum.
//----

//---- Requirement
[[g4-exp5]]
^`G.4.{counter:g4}`^
The system should be able to send a notification when his capacity is full or near full (80%).
//----

//---- Requirement
[[g4-exp6]]
^`G.4.{counter:g4}`^
The system shall be open to be emptied by the user at any given time.
//----

=== G.5 High-level usage scenarios 

//---- Requirement
[[g5-exp]]
^`G.5.{counter:g4}`^
The system shall read any standard A4 letter within any standard envelope and send it by email to the user.
//----

=== G.6 Limitations and exclusions 

//---- Requirement
[[g6-exp1]]
^`G.6.{counter:g6}`^
The system shall not be able to read any letter that is not a standard A4 letter.
//----

//---- Requirement
[[g6-exp2]]
^`G.6.{counter:g6}`^
The system shall send any email to any email address that is not registered by the user, including previous email adresses.
//----

=== G.7 Stakeholders and requirements sources

// generate
//---- Requirement
[[g7-exp1]]
^`G.7.{counter:g7}`^
*Users* The end user of the system, who will benefit from the system's functionalities.
//----

//---- Requirement
[[g7-exp2]]
^`G.7.{counter:g7}`^
*Letter carrier* The person in charge of the delivery of letters.
//----

//---- Requirement
[[g7-exp3]]
^`G.7.{counter:g7}`^
*Package carrier* The person in charge of the delivery of packages.
//----

//------------------------------------
// ENVIRONMENT book
//
// Template for requirement:
//[[ex-keyword]] 
//`{counter:environment}`
// Requirement

// {missing} [Corresponding Artifact]
//------------------------------------
== Environment

=== E.1 Glossary

Example of terms definition.

[[e1-terms]]
==== `E.1.{counter:e1}` Terms

[[Book]]
{Book}:: Copy of a book with a copy number and an availability status.

[[Catalog]]
{Catalog}:: List of library <<Book,books>> and their instance availability.

=== E.2 Components

//---- Requirement
[[e2-exp1]]
^`E.2.{counter:e2}`^
The system will need to be connected to the Internet to send emails.


*   [[e2-exp1.1]]
    ^`E.2.{counter:e2}`^
    The system will have a physical link to the Internet through an Ethernet cable.

*   [[e2-exp1.2]]
    ^`E.2.{counter:e2}`^
    The system will have to send requests to emailing servers/services (SMTP, POP, IMAP)

//----

//---- Requirement
[[e2-exp2]]
^`E.2.{counter:e2}`^
The system will need to be using a camera or scanner-like technology to read the content of the letters.
//----

//---- Requirement
[[e2-exp6]]
^`E.2.{counter:e2}`^
The system will need to have an interface (physical or software) to allow the user to register his email addresses
//----


=== E.3 Constraints

//---- Requirement
[[e3-exp1]]
^`E.3.{counter:e3}`^
The size of the {BAL} is constraint by the law to of the following dimensions:

    * Dimensions minimales pour les habitations individuelles
    ** Flap dimensions : 26 cm width * 3 cm height
    ** Outer-box : 34 cm width * 26 cm height * 26 cm depth
    
    * Dimensions minimales pour les habitations collectives
    ** Chaque compartiment doit pouvoir contenir un volume de 260 mm (largeur) x 260 mm (hauteur) x 340 mm (profondeur)

//----

NOTE: Obligations and limits imposed on the project and system by the environment (see {Handbook}).

WARNING: This chapter should not be empty (following the _Minimum Requirements Outcome Principle_, p.27 of the {handbook}).

=== E.4 Assumptions

NOTE: Properties of the environment that may be assumed, with the goal of facilitating the project and simplifying the system (see {Handbook}).

{emptysec}

=== E.5 Effects

NOTE: Elements and properties of the environment that the system will affect (see {Handbook}).

{emptysec}

=== E.6 Invariants

NOTE: Properties of the environment that the system’s operation must preserve (see {Handbook}).

{emptysec}

//------------------------------------
// SYSTEM book
//
// Template for requirement:
//---- Requirement
//[[sx-keyword]] 
//`{counter:sx}`
// Requirement

// {missing} [Corresponding Artifact]
//---- 
//------------------------------------

== System

NOTE: The System book refines the Goal one by focusing on more detailed requirements about the system under development, mainly its constituents, behaviors and properties.

=== S.1 Components

NOTE: Overall structure expressed by the list of major software and, if applicable, hardware parts (see {Handbook}).

WARNING: This chapter should not be empty (following the _Minimum Requirements Outcome Principle_, p.27 of the {handbook}).

=== S.2 Functionality

NOTE: One section, S.2.n, for each of the components identified in S.1, describing the corresponding behaviors (functional and non-functional properties; see {Handbook}).

WARNING: This chapter should not be empty (following the _Minimum Requirements Outcome Principle_, p.27 of the {handbook}).

=== S.3 Interfaces

NOTE: How the system makes the functionality of S.2 available to the rest of the world, particularly user interfaces and program interfaces (APIs) (see {Handbook}).

{emptysec}

=== S.4 Detailed usage scenarios

NOTE: Examples of interaction between the environment (or human users) and the system: use cases, user stories (see {Handbook}).

{emptysec}

=== S.5 Prioritization

NOTE: Classification of the behaviors, interfaces and scenarios (S.2, S.3 and S.4) by their degree of criticality (see {Handbook}).

{emptysec}

=== S.6 Verification and acceptance criteria

NOTE: Specification of the conditions under which an implementation will be deemed satisfactory (see {Handbook}).

{emptysec}

//------------------------------------
// PROJECT book
//
// Template for requirement:
//[[ex-keyword]] 
//`{counter:project}`
// Requirement

// {missing} [Corresponding Artifact]
//------------------------------------
== Project

NOTE: The Project book describes all the constraints and expectations not about the system itself, but about how to develop and produce it.

=== P.1 Roles and personnel

NOTE: Main responsibilities in the project; required project staff and their needed qualifications (see {Handbook}).

{emptysec}

=== P.2 Imposed technical choices

NOTE: Any a priori choices binding the project to specific tools, hardware, languages or other technical parameters (see {Handbook}).

{emptysec}

=== P.3 Schedule and milestones

NOTE: List of tasks to be carried out and their scheduling (see {Handbook}).

WARNING: This chapter should not be empty (following the _Minimum Requirements Outcome Principle_, p.27 of the {handbook}).

=== P.4 Tasks and deliverables

NOTE: Details of individual tasks listed under P.3 and their expected outcomes (see {Handbook}).

WARNING: This chapter should not be empty (following the _Minimum Requirements Outcome Principle_, p.27 of the {handbook}).

=== P.5 Required technology elements

NOTE: External systems, hardware and software, expected to be necessary for building the system (see {Handbook}).

{emptysec}

=== P.6 Risk and mitigation analysis

NOTE: Potential obstacles to meeting the schedule of P.4, and measures for adapting the plan if they do arise (see {Handbook}).

{emptysec}

=== P.7 Requirements process and report

NOTE: Initially, description of what the requirements process will be; later, report on its steps (see {Handbook}).

{emptysec}

